apiVersion: v1
kind: Secret
metadata:
  name: gitlab-token
  labels:
    {{- include "obs-gitlab-runner.labels" . | nindent 4 }}
type: Opaque
{{- $previous := lookup "v1" "Secret" .Release.Namespace "gitlab-token" }}
data:
  {{- if .Values.gitlab.token }}
  token: {{ .Values.gitlab.token | b64enc | quote }}
  {{- else if $previous }}
  token: {{ $previous.data.token }}
  {{- else }}
  {{- fail "gitlab.token must be set for the initial install" }}
  {{- end }}
